//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchievementStatistic
    {
        public int UserID { get; set; }
        public Nullable<int> LevelNumber { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> PurchasedCategoryCount { get; set; }
        public Nullable<int> PurchasedAvatarCount { get; set; }
        public Nullable<int> PurchasedThemeCount { get; set; }
        public Nullable<int> CreatedQuestionsCount { get; set; }
    }
}
