//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppAdvertisement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppAdvertisement()
        {
            this.PresentedAdverts = new HashSet<PresentedAdvert>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string BackgroundColor { get; set; }
        public string MarketPackageName { get; set; }
        public string MarketIntentString { get; set; }
        public string AppStoreUri { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime ExpireTime { get; set; }
        public int Priority { get; set; }
        public bool IsNew { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresentedAdvert> PresentedAdverts { get; set; }
    }
}
