//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationState
    {
        public int ID { get; set; }
        public int Favorite_FavoritePrice { get; set; }
        public int Favorite_FreeNumberToFavorite { get; set; }
        public string User_DefaultUserName { get; set; }
        public int User_DefaultUserCoin { get; set; }
        public int Question_CreateQuestionPrice { get; set; }
        public int Question_DefaultReturnAmount { get; set; }
        public int Question_NumberToSkip { get; set; }
        public string Question_NoQuestionFoundWhat { get; set; }
        public string Question_NoQuestionFoundBut { get; set; }
        public int Question_NoQuestionFoundID { get; set; }
        public int Question_ServerBurntReturnAmount { get; set; }
        public int Prize_AnswerPrize { get; set; }
        public int Prize_LikePrize { get; set; }
        public int Prize_CreateNewQuestionPrize { get; set; }
        public int Prize_NewQuestionAcceptedPrize { get; set; }
        public int Paging_DefaultPageSize { get; set; }
        public int Leader_TopNumberToShow { get; set; }
        public int Comment_DefaultNumberAmount { get; set; }
        public bool Comment_DefaultVerifyState { get; set; }
        public string Host_WebSiteNoReplyMail { get; set; }
        public string Host_WebSiteNoReplyMailPassword { get; set; }
        public string Host_SupportMail { get; set; }
        public string Host_SupportMailPassword { get; set; }
        public string Host_SmtpServer { get; set; }
        public int Store_DefaultReturnAmount { get; set; }
    }
}
