//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationState
    {
        public int ID { get; set; }
        public int FavoritePrice { get; set; }
        public string DefaultUserName { get; set; }
        public int DefaultUserCoin { get; set; }
        public int CreateQuestionPrice { get; set; }
    }
}
