//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReward
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public int Day { get; set; }
        public int Prize { get; set; }
    }
}
