//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameConfig
    {
        public int ID { get; set; }
        public int TotalNumberOfQuestions { get; set; }
        public int HighQualityQuestionsPercent { get; set; }
        public int FunQuestionsPercent { get; set; }
        public int NewCreatedQuestionsPercent { get; set; }
        public int DefaultUserCoinAmount { get; set; }
        public int DefaultUserLevelNumber { get; set; }
        public int DefaultUserLevelProgress { get; set; }
        public int MaxReportCount { get; set; }
    }
}
