//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationSystemConfiguration
    {
        public int ID { get; set; }
        public string NotificationName { get; set; }
        public string NotificationURL { get; set; }
        public string NotificationKey { get; set; }
        public string NotificationAppID { get; set; }
        public string FriendRequest_Title { get; set; }
        public string SentRequest_Title { get; set; }
        public string InboxRequest_Title { get; set; }
        public string FriendResponse_Title { get; set; }
        public string FriendRequest_Description { get; set; }
        public string SentRequest_Description { get; set; }
        public string InboxRequest_Description { get; set; }
        public string FriendResponse_Description { get; set; }
        public string FriendRequest_Image { get; set; }
        public string SentRequest_Image { get; set; }
        public string InboxRequest_Image { get; set; }
        public string FriendResponse_Image { get; set; }
    }
}
