//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHistory
    {
        public int ID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public int Price { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
