//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestPeopleScore
    {
        public int ID { get; set; }
        public int LevelNumber { get; set; }
        public int QuestNumber { get; set; }
        public double MeanScorePoint { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Quest Quest { get; set; }
    }
}
