//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public int UserOneID { get; set; }
        public int UserTwoID { get; set; }
        public int RelationStatus { get; set; }
        public int OperatedByID { get; set; }
        public int ID { get; set; }
    
        public virtual RelationshipStatu RelationshipStatu { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
