//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpinWheel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpinWheel()
        {
            this.AchievedSpinWheels = new HashSet<AchievedSpinWheel>();
            this.UnRepeatableAchievedSpinWheels = new HashSet<UnRepeatableAchievedSpinWheel>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; }
        public int SpinWheelTypeID { get; set; }
        public int Prize { get; set; }
        public int SpinWheelAlternativeID { get; set; }
        public int FirstChance { get; set; }
        public int SecondChance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AchievedSpinWheel> AchievedSpinWheels { get; set; }
        public virtual SpinWheelType SpinWheelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnRepeatableAchievedSpinWheel> UnRepeatableAchievedSpinWheels { get; set; }
    }
}
