//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string GoogleID { get; set; }
        public bool IsVerified { get; set; }
        public bool IsBanned { get; set; }
        public int IsEditable { get; set; }
        public System.DateTime RegisterDateTime { get; set; }
        public Nullable<System.DateTime> ChangeInfoDate { get; set; }
        public bool IsEnable { get; set; }
    
        public virtual User User { get; set; }
    }
}
