//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStat
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int Score { get; set; }
        public int OldScore { get; set; }
        public int Rank { get; set; }
        public int SpinRemainedChance { get; set; }
        public int SpinWheelCount { get; set; }
    
        public virtual User User { get; set; }
    }
}
