//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.EFCommonContext.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AchievedCodeGifts = new HashSet<AchievedCodeGift>();
            this.Answers = new HashSet<Answer>();
            this.Manufactures = new HashSet<Manufacture>();
            this.Orders = new HashSet<Order>();
            this.ReportedQuestions = new HashSet<ReportedQuestion>();
            this.UserInfoes = new HashSet<UserInfo>();
            this.WatchedAds = new HashSet<WatchedAd>();
        }
    
        public int ID { get; set; }
        public string UUID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public int TotalCoin { get; set; }
        public int LevelProgress { get; set; }
        public Nullable<int> CurrentLevelNumber { get; set; }
        public bool IsAbleToWriteComment { get; set; }
        public System.DateTime LastSeenDateTime { get; set; }
        public System.DateTime PrevLastSeenDateTime { get; set; }
        public System.DateTime PreviousDaySeen { get; set; }
        public int DWMCount { get; set; }
        public bool IsTutorial { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AchievedCodeGift> AchievedCodeGifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Level Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manufacture> Manufactures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportedQuestion> ReportedQuestions { get; set; }
        public virtual UserType UserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WatchedAd> WatchedAds { get; set; }
    }
}
